export const coreTypes = ["string", "int", "float", "bool", "scope", "auto"];

export const coreFunctions = [
  "print",
  "str",
  "bool",
  "int",
  "float",
  "createFolder",
  "removeFolder",
  "createFile",
  "readFile",
  "writeFile",
  "writeToLine",
  "writeToMultipleLines",
  "removeFile",
  "copyFile",
  "writeLocalisation",
  "convertToDds",
  "pathExists",
  "getFilenameFromPath",
  "find",
  "replaceAll",
  "len",
  "HPL_throwError",
];
